### ISSUE TITLE
Incompatibility with /invsee command on Bukkit/Spigot servers

### ISSUE THREAD

**Issue by JesseMcCullough** [Dartanman/Dssentials#1]
In [Invsee](https://github.com/Dartanman/Dssentials/blob/master/src/main/dartanman/dssentials/commands/Invsee.java), [the import for ChatColor](https://github.com/Dartanman/Dssentials/blob/master/src/main/dartanman/dssentials/commands/Invsee.java#L7) comes from the BungeeCord API, which isn't compatible with Bukkit/Spigot servers. To fix this, ChatColor needs to come from the Bukkit API (org.bukkit), not the BungeeCord API (net.md_5.bungee.api).

**Comment by Dartanman** [comment]
Oops. I must have forgotten to change it to org.bukkit
Thank you for seeing that! I'll fix it!
